//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTycoon.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolTycoon.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs.
        /// </summary>
        internal static string ClassroomBuilderCosts {
            get {
                return ResourceManager.GetString("ClassroomBuilderCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An elongated classroom with room for 36 pupils. The extra space in the back allows for groups of 4 tables, so-called &apos;islands&apos;, to be put together for a more pleasant learning environment..
        /// </summary>
        internal static string ClassroomMediumDescription {
            get {
                return ResourceManager.GetString("ClassroomMediumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom (Medium).
        /// </summary>
        internal static string ClassroomMediumName {
            get {
                return ResourceManager.GetString("ClassroomMediumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compact classroom that can accommodate up to 24 pupils. There is just enough room for a blackboard and some cupboards. Can be used for all subjects, but not very suitable for group activities..
        /// </summary>
        internal static string ClassroomSmallDescription {
            get {
                return ResourceManager.GetString("ClassroomSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom (Small).
        /// </summary>
        internal static string ClassroomSmallName {
            get {
                return ResourceManager.GetString("ClassroomSmallName", resourceCulture);
            }
        }
    }
}
