//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTycoon.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Nederlands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nederlands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolTycoon.Languages.Nederlands", typeof(Nederlands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten: €{0}.
        /// </summary>
        internal static string ClassroomBuilderCosts {
            get {
                return ResourceManager.GetString("ClassroomBuilderCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouwtijd: {0} dagen.
        /// </summary>
        internal static string ClassroomBuilderTime {
            get {
                return ResourceManager.GetString("ClassroomBuilderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een enorm klaslokaal met ruime plek voor ongeveer 48 leerlingen. Naast een toegeweid gebied voor groepactiviteiten is er een technologische hoek dat kan dienen als laboratorium of computerruimte..
        /// </summary>
        internal static string ClassroomLargeDescription {
            get {
                return ResourceManager.GetString("ClassroomLargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaslokaal (Groot).
        /// </summary>
        internal static string ClassroomLargeName {
            get {
                return ResourceManager.GetString("ClassroomLargeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een verlengd klaslokaal met plaats voor 36 leerlingen. De extra ruimte achterin biedt mogelijkheden groepen te vormen van 4 tafels, zogenaamde &apos;eilandjes&apos;, voor een aangenamere leeromgeving..
        /// </summary>
        internal static string ClassroomMediumDescription {
            get {
                return ResourceManager.GetString("ClassroomMediumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaslokaal (Medium).
        /// </summary>
        internal static string ClassroomMediumName {
            get {
                return ResourceManager.GetString("ClassroomMediumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een compact klaslokaal dat plaatsen biedt voor 24 leerlingen. Er is net genoeg ruimte voor een schoolbord en wat kasten. Kan voor alle vakken gebruikt worden, maar is niet erg geschikt voor groepsactiviteiten..
        /// </summary>
        internal static string ClassroomSmallDescription {
            get {
                return ResourceManager.GetString("ClassroomSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaslokaal (Klein).
        /// </summary>
        internal static string ClassroomSmallName {
            get {
                return ResourceManager.GetString("ClassroomSmallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} {0}, {3}e jaar.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
    }
}
