//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTycoon.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolTycoon.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A must-have for any classroom. In fact, it wouldn&apos;t even be a classroom without one of these; it would be just a room. The meager writing space leaves something to be desired..
        /// </summary>
        internal static string ChalkboardDescription {
            get {
                return ResourceManager.GetString("ChalkboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chalkboard.
        /// </summary>
        internal static string ChalkboardName {
            get {
                return ResourceManager.GetString("ChalkboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs: €{0}.
        /// </summary>
        internal static string ClassroomBuilderCosts {
            get {
                return ResourceManager.GetString("ClassroomBuilderCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building time: {0} days.
        /// </summary>
        internal static string ClassroomBuilderTime {
            get {
                return ResourceManager.GetString("ClassroomBuilderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vast classroom with ample space for roughly 48 pupils. In addition to a dedicated group activity area, there is a technology corner that can be used as a laboratory or computer facility..
        /// </summary>
        internal static string ClassroomLargeDescription {
            get {
                return ResourceManager.GetString("ClassroomLargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom (Large).
        /// </summary>
        internal static string ClassroomLargeName {
            get {
                return ResourceManager.GetString("ClassroomLargeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An elongated classroom with room for 36 pupils. The extra space in the back allows for groups of 4 tables, so-called &apos;islands&apos;, to be put together for a more pleasant learning environment..
        /// </summary>
        internal static string ClassroomMediumDescription {
            get {
                return ResourceManager.GetString("ClassroomMediumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom (Medium).
        /// </summary>
        internal static string ClassroomMediumName {
            get {
                return ResourceManager.GetString("ClassroomMediumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compact classroom that can accommodate up to 24 pupils. There is just enough room for a blackboard and some cupboards. Can be used for all subjects, but not very suitable for group activities..
        /// </summary>
        internal static string ClassroomSmallDescription {
            get {
                return ResourceManager.GetString("ClassroomSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom (Small).
        /// </summary>
        internal static string ClassroomSmallName {
            get {
                return ResourceManager.GetString("ClassroomSmallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}{2}, year {3}.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chalkboard that you can fold open for extra writing space. This lets you re-use images for another lesson and write down walls of text..
        /// </summary>
        internal static string DoubleChalkboardDescription {
            get {
                return ResourceManager.GetString("DoubleChalkboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Chalkboard.
        /// </summary>
        internal static string DoubleChalkboardName {
            get {
                return ResourceManager.GetString("DoubleChalkboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A super-long whiteboard with ample writing space. It can be folded to provide additional room, or to cover up embarrasingly bad diagrams..
        /// </summary>
        internal static string DoubleWhiteboardDescription {
            get {
                return ResourceManager.GetString("DoubleWhiteboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Whiteboard.
        /// </summary>
        internal static string DoubleWhiteboardName {
            get {
                return ResourceManager.GetString("DoubleWhiteboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shockingly useful giant touch screen hooked up to a computer, to be used for displaying web pages and images, or playing this game..
        /// </summary>
        internal static string InteractiveWhiteboardDescription {
            get {
                return ResourceManager.GetString("InteractiveWhiteboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Whiteboard.
        /// </summary>
        internal static string InteractiveWhiteboardName {
            get {
                return ResourceManager.GetString("InteractiveWhiteboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a rock. You chisel stuff on it. Not much else to say.
        ///
        ///By the way, it doesn&apos;t come with a chisel..
        /// </summary>
        internal static string RockSlateDescription {
            get {
                return ResourceManager.GetString("RockSlateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Slate.
        /// </summary>
        internal static string RockSlateName {
            get {
                return ResourceManager.GetString("RockSlateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like a chalkboard, except it uses ink instead of chalk. Perfect for colourful graphs, tables and pictures of dinosaurs, but you can&apos;t fit many of them on it..
        /// </summary>
        internal static string WhiteboardDescription {
            get {
                return ResourceManager.GetString("WhiteboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whiteboard.
        /// </summary>
        internal static string WhiteboardName {
            get {
                return ResourceManager.GetString("WhiteboardName", resourceCulture);
            }
        }
    }
}
