//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTycoon.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Nederlands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nederlands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolTycoon.Languages.Nederlands", typeof(Nederlands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een vereiste voor ieder klaslokaal. Eigenlijk zou het niet eens een klaslokaal zijn zonder een van deze, maar gewoon een kamer. De armzalige schrijfruimte laat te wensen over..
        /// </summary>
        internal static string ChalkboardDescription {
            get {
                return ResourceManager.GetString("ChalkboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krijtbord.
        /// </summary>
        internal static string ChalkboardName {
            get {
                return ResourceManager.GetString("ChalkboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten: €{0}.
        /// </summary>
        internal static string ClassroomBuilderCosts {
            get {
                return ResourceManager.GetString("ClassroomBuilderCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouwtijd: {0} dagen.
        /// </summary>
        internal static string ClassroomBuilderTime {
            get {
                return ResourceManager.GetString("ClassroomBuilderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een enorm klaslokaal met ruime plek voor ongeveer 48 leerlingen. Naast een toegeweid gebied voor groepactiviteiten is er een technologische hoek dat kan dienen als laboratorium of computerruimte..
        /// </summary>
        internal static string ClassroomLargeDescription {
            get {
                return ResourceManager.GetString("ClassroomLargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaslokaal (Groot).
        /// </summary>
        internal static string ClassroomLargeName {
            get {
                return ResourceManager.GetString("ClassroomLargeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een verlengd klaslokaal met plaats voor 36 leerlingen. De extra ruimte achterin biedt mogelijkheden groepen te vormen van 4 tafels, zogenaamde &apos;eilandjes&apos;, voor een aangenamere leeromgeving..
        /// </summary>
        internal static string ClassroomMediumDescription {
            get {
                return ResourceManager.GetString("ClassroomMediumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaslokaal (Medium).
        /// </summary>
        internal static string ClassroomMediumName {
            get {
                return ResourceManager.GetString("ClassroomMediumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een compact klaslokaal dat plaatsen biedt voor 24 leerlingen. Er is net genoeg ruimte voor een schoolbord en wat kasten. Kan voor alle vakken gebruikt worden, maar is niet erg geschikt voor groepsactiviteiten..
        /// </summary>
        internal static string ClassroomSmallDescription {
            get {
                return ResourceManager.GetString("ClassroomSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaslokaal (Klein).
        /// </summary>
        internal static string ClassroomSmallName {
            get {
                return ResourceManager.GetString("ClassroomSmallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} {0}, {3}e jaar.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A krijtbord dat je open kunt klappen voor extra schrijfruimte. Hierdoor kun je afbeeldingen tijdens een andere les opnieuw gebruiken, of het bord volkladderen met tekst..
        /// </summary>
        internal static string DoubleChalkboardDescription {
            get {
                return ResourceManager.GetString("DoubleChalkboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubbel Krijtbord.
        /// </summary>
        internal static string DoubleChalkboardName {
            get {
                return ResourceManager.GetString("DoubleChalkboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een superlang witbord met schrijfruimte in overvloed. Hij kan opengeklapt worden om extra ruimte te kunnen gebruiken, of beschamend lelijke diagrammen te verbergen..
        /// </summary>
        internal static string DoubleWhiteboardDescription {
            get {
                return ResourceManager.GetString("DoubleWhiteboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubbel Witbord.
        /// </summary>
        internal static string DoubleWhiteboardName {
            get {
                return ResourceManager.GetString("DoubleWhiteboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een schokkend handig enorm aanraakscherm verbonden met een computer, te gebruiken om webpaginas en afbeeldingen te tonen, of dit spel te spelen..
        /// </summary>
        internal static string InteractiveWhiteboardDescription {
            get {
                return ResourceManager.GetString("InteractiveWhiteboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactief Witbord.
        /// </summary>
        internal static string InteractiveWhiteboardName {
            get {
                return ResourceManager.GetString("InteractiveWhiteboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit is een steen. Je beitelt er dingen op. Valt niet veel meer over te zeggen.
        ///
        ///Beitel niet inbegrepen..
        /// </summary>
        internal static string RockSlateDescription {
            get {
                return ResourceManager.GetString("RockSlateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leisteen.
        /// </summary>
        internal static string RockSlateName {
            get {
                return ResourceManager.GetString("RockSlateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net een krijtbord, maar dan met inkt in plaats van krijt. Perfect voor kleurrijke grafieken, tabellen en plaatjes van dinosaurussen, maar er passen er niet veel van op..
        /// </summary>
        internal static string WhiteboardDescription {
            get {
                return ResourceManager.GetString("WhiteboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witbord.
        /// </summary>
        internal static string WhiteboardName {
            get {
                return ResourceManager.GetString("WhiteboardName", resourceCulture);
            }
        }
    }
}
